language: r
warnings_are_errors: false
env: _R_CHECK_CRAN_INCOMING_=FALSE

r_github_packages:
  - jimhester/covr
  - allr/rcov

after_success:
  - source shim_package.sh
  - Rscript -e 'library(covr);coveralls()'
